/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CoordinatorRouteImport } from './routes/coordinator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as NotificationDiagnosticsRouteImport } from './routes/notification-diagnostics'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuditoriumsIndexRouteImport } from './routes/auditoriums.index'
import { Route as AuditoriumsIdRouteImport } from './routes/auditoriums.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as SubmittedIdRouteImport } from './routes/submitted.$id'
import { Route as BookingsIdIndexRouteImport } from './routes/bookings.$id.index'
import { Route as BookingsIdConfirmedRouteImport } from './routes/bookings.$id.confirmed'
import { Route as BookingsIdUploadRouteImport } from './routes/bookings.$id.upload'
import { Route as BookingsIdVerificationRouteImport } from './routes/bookings.$id.verification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRoute = CoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationDiagnosticsRoute = NotificationDiagnosticsRouteImport.update({
  id: '/notification-diagnostics',
  path: '/notification-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriumsIndexRoute = AuditoriumsIndexRouteImport.update({
  id: '/auditoriums/',
  path: '/auditoriums/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriumsIdRoute = AuditoriumsIdRouteImport.update({
  id: '/auditoriums/$id',
  path: '/auditoriums/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedIdRoute = SubmittedIdRouteImport.update({
  id: '/submitted/$id',
  path: '/submitted/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdIndexRoute = BookingsIdIndexRouteImport.update({
  id: '/bookings/$id/',
  path: '/bookings/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdConfirmedRoute = BookingsIdConfirmedRouteImport.update({
  id: '/bookings/$id/confirmed',
  path: '/bookings/$id/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdUploadRoute = BookingsIdUploadRouteImport.update({
  id: '/bookings/$id/upload',
  path: '/bookings/$id/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdVerificationRoute = BookingsIdVerificationRouteImport.update({
  id: '/bookings/$id/verification',
  path: '/bookings/$id/verification',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/coordinator': typeof CoordinatorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/notification-diagnostics': typeof NotificationDiagnosticsRoute
  '/notifications': typeof NotificationsRoute
  '/organizer': typeof OrganizerRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/welcome': typeof WelcomeRoute
  '/auditoriums/$id': typeof AuditoriumsIdRoute
  '/book/$id': typeof BookIdRoute
  '/submitted/$id': typeof SubmittedIdRoute
  '/auditoriums/': typeof AuditoriumsIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/bookings/$id/confirmed': typeof BookingsIdConfirmedRoute
  '/bookings/$id/upload': typeof BookingsIdUploadRoute
  '/bookings/$id/verification': typeof BookingsIdVerificationRoute
  '/bookings/$id/': typeof BookingsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/coordinator': typeof CoordinatorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/notification-diagnostics': typeof NotificationDiagnosticsRoute
  '/notifications': typeof NotificationsRoute
  '/organizer': typeof OrganizerRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/welcome': typeof WelcomeRoute
  '/auditoriums/$id': typeof AuditoriumsIdRoute
  '/book/$id': typeof BookIdRoute
  '/submitted/$id': typeof SubmittedIdRoute
  '/auditoriums': typeof AuditoriumsIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/bookings/$id/confirmed': typeof BookingsIdConfirmedRoute
  '/bookings/$id/upload': typeof BookingsIdUploadRoute
  '/bookings/$id/verification': typeof BookingsIdVerificationRoute
  '/bookings/$id': typeof BookingsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/coordinator': typeof CoordinatorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/notification-diagnostics': typeof NotificationDiagnosticsRoute
  '/notifications': typeof NotificationsRoute
  '/organizer': typeof OrganizerRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/welcome': typeof WelcomeRoute
  '/auditoriums/$id': typeof AuditoriumsIdRoute
  '/book/$id': typeof BookIdRoute
  '/submitted/$id': typeof SubmittedIdRoute
  '/auditoriums/': typeof AuditoriumsIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/bookings/$id/confirmed': typeof BookingsIdConfirmedRoute
  '/bookings/$id/upload': typeof BookingsIdUploadRoute
  '/bookings/$id/verification': typeof BookingsIdVerificationRoute
  '/bookings/$id/': typeof BookingsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/coordinator'
    | '/login'
    | '/logout'
    | '/notification-diagnostics'
    | '/notifications'
    | '/organizer'
    | '/profile'
    | '/review'
    | '/sitemap.xml'
    | '/super-admin'
    | '/welcome'
    | '/auditoriums/$id'
    | '/book/$id'
    | '/submitted/$id'
    | '/auditoriums/'
    | '/bookings/'
    | '/bookings/$id/confirmed'
    | '/bookings/$id/upload'
    | '/bookings/$id/verification'
    | '/bookings/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/coordinator'
    | '/login'
    | '/logout'
    | '/notification-diagnostics'
    | '/notifications'
    | '/organizer'
    | '/profile'
    | '/review'
    | '/sitemap.xml'
    | '/super-admin'
    | '/welcome'
    | '/auditoriums/$id'
    | '/book/$id'
    | '/submitted/$id'
    | '/auditoriums'
    | '/bookings'
    | '/bookings/$id/confirmed'
    | '/bookings/$id/upload'
    | '/bookings/$id/verification'
    | '/bookings/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/coordinator'
    | '/login'
    | '/logout'
    | '/notification-diagnostics'
    | '/notifications'
    | '/organizer'
    | '/profile'
    | '/review'
    | '/sitemap.xml'
    | '/super-admin'
    | '/welcome'
    | '/auditoriums/$id'
    | '/book/$id'
    | '/submitted/$id'
    | '/auditoriums/'
    | '/bookings/'
    | '/bookings/$id/confirmed'
    | '/bookings/$id/upload'
    | '/bookings/$id/verification'
    | '/bookings/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  CoordinatorRoute: typeof CoordinatorRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  NotificationDiagnosticsRoute: typeof NotificationDiagnosticsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizerRoute: typeof OrganizerRoute
  ProfileRoute: typeof ProfileRoute
  ReviewRoute: typeof ReviewRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperAdminRoute: typeof SuperAdminRoute
  WelcomeRoute: typeof WelcomeRoute
  AuditoriumsIdRoute: typeof AuditoriumsIdRoute
  BookIdRoute: typeof BookIdRoute
  SubmittedIdRoute: typeof SubmittedIdRoute
  AuditoriumsIndexRoute: typeof AuditoriumsIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  BookingsIdConfirmedRoute: typeof BookingsIdConfirmedRoute
  BookingsIdUploadRoute: typeof BookingsIdUploadRoute
  BookingsIdVerificationRoute: typeof BookingsIdVerificationRoute
  BookingsIdIndexRoute: typeof BookingsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator': {
      id: '/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-diagnostics': {
      id: '/notification-diagnostics'
      path: '/notification-diagnostics'
      fullPath: '/notification-diagnostics'
      preLoaderRoute: typeof NotificationDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoriums/': {
      id: '/auditoriums/'
      path: '/auditoriums'
      fullPath: '/auditoriums/'
      preLoaderRoute: typeof AuditoriumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoriums/$id': {
      id: '/auditoriums/$id'
      path: '/auditoriums/$id'
      fullPath: '/auditoriums/$id'
      preLoaderRoute: typeof AuditoriumsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted/$id': {
      id: '/submitted/$id'
      path: '/submitted/$id'
      fullPath: '/submitted/$id'
      preLoaderRoute: typeof SubmittedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/': {
      id: '/bookings/$id/'
      path: '/bookings/$id'
      fullPath: '/bookings/$id/'
      preLoaderRoute: typeof BookingsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/confirmed': {
      id: '/bookings/$id/confirmed'
      path: '/bookings/$id/confirmed'
      fullPath: '/bookings/$id/confirmed'
      preLoaderRoute: typeof BookingsIdConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/upload': {
      id: '/bookings/$id/upload'
      path: '/bookings/$id/upload'
      fullPath: '/bookings/$id/upload'
      preLoaderRoute: typeof BookingsIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/verification': {
      id: '/bookings/$id/verification'
      path: '/bookings/$id/verification'
      fullPath: '/bookings/$id/verification'
      preLoaderRoute: typeof BookingsIdVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  CoordinatorRoute: CoordinatorRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  NotificationDiagnosticsRoute: NotificationDiagnosticsRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizerRoute: OrganizerRoute,
  ProfileRoute: ProfileRoute,
  ReviewRoute: ReviewRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperAdminRoute: SuperAdminRoute,
  WelcomeRoute: WelcomeRoute,
  AuditoriumsIdRoute: AuditoriumsIdRoute,
  BookIdRoute: BookIdRoute,
  SubmittedIdRoute: SubmittedIdRoute,
  AuditoriumsIndexRoute: AuditoriumsIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  BookingsIdConfirmedRoute: BookingsIdConfirmedRoute,
  BookingsIdUploadRoute: BookingsIdUploadRoute,
  BookingsIdVerificationRoute: BookingsIdVerificationRoute,
  BookingsIdIndexRoute: BookingsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
